trigger:
  branches:
    include:
      - main
pr:
  none

pool:
  vmImage: 'ubuntu-latest'

variables:
  location: 'uksouth'
  resourceGroup: 'bicep-app'

stages:
  - stage: Deploy
    jobs:
      - job: DeployBicep
        steps:
        - checkout: self
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'Azure subscription 1(525c7c1f-f5e9-4bf4-8d7a-5b7a06889a12)'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              echo "Installing Bicep CLI..."
              az bicep install
              echo "Validating Bicep..."
              az bicep build --file ./Infrastructure/main.bicep
              echo "Deploying Bicep to Azure..."
              az deployment group create \
                --resource-group bicep-app \
                --template-file ./main.bicep \
                --parameters environment='dev' location='uksouth'
